services:
  backend:
    container_name: anrapp-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - appnet
  nginx:
    image: nginx:latest
    container_name: anrapp-nginx
    depends_on:
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./nginx/default-site.conf:/etc/nginx/conf.d/default-site.conf:ro
    restart: unless-stopped
    ports:
      - 8800:80
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
